### ISSUE TITLE
Need step by step procedure

### ISSUE THREAD

**Issue by akash-s-ksgd** [angstyfrostyneko/spotify-to-vimusic#1]
Please give step by step procedure to import spotify playlist to vi music

**Comment by angstyfrostyneko** [comment]
**Step 1: Export Spotify Playlist**
Go to Spotlistr (or any similar service) and export your Spotify playlist to a text file.
Open the `spotify_playlist.txt` file and ensure it's correctly formatted with songs and artists separated by a pipe `|`. If not, manually edit it to match the required format.
Rename the file to `songlist.txt`.

**Step 2: Export ViMusic Database**
Open ViMusic and export a backup of your database.
Rename the exported file to `database.db`.

**Step 3: Prepare the Environment**
Open your terminal or command prompt.
Install the necessary Python packages using pip:
`pip install ytmusicapi thefuzz cutlet`
Place the `songlist.txt` and `database.db` files in the same folder as `spotifytovimusic.py`.

**Step 4: Run the Python Script**
Run the Python script `spotifytovimusic.py`.
`python spotifytovimusic.py`
Wait until the script finishes processing.

**Step 5: Reimport the Database into ViMusic**
After the script has finished running, you'll have an updated `database.db` file in the same folder.
Open ViMusic and import the modified `database.db` file.

**Comment by akash-s-ksgd** [comment]
can't find '__main__' module in 'C:\\Users\\ASUS\\spotifytovimusic.py'

**Comment by akash-s-ksgd** [comment]
I am kinda new to this platform so need to learn somethings.
